version: '3'

networks: 
  app-network: 
  # backend_app-network:
  #   external: true

services: 
  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: nginx_${APP_NAME}
  #   ports: 
  #       - 80:80
  #   volumes: 
  #       - ./:/var/www/html
  #       - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
  #   networks: 
  #       - app-network
  node:
    build:
      context: .
      dockerfile: node.dockerfile
    container_name: node_${APP_NAME}
    volumes: 
      - ./:/var/www/html
    command: yarn serve
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
    networks: 
      - app-network
